// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CollapsibleController from "./collapsible_controller"
application.register("collapsible", CollapsibleController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import ExpandCollapseController from "./expand_collapse_controller"
application.register("expand-collapse", ExpandCollapseController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MobileMenuController from "./mobile_menu_controller"
application.register("mobile-menu", MobileMenuController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import StructureController from "./structure_controller"
application.register("structure", StructureController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import TagInputController from "./tag_input_controller"
application.register("tag-input", TagInputController)
